/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',

    config: {
        itemId: 'mainWindow',
        ui: 'light',
        layout: {
            animation: 'slide',
            type: 'card'
        },
        items: [
            {
                xtype: 'panel',
                autoDestroy: false,
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        title: '&lt;Character Name&gt;',
                        items: [
                            {
                                xtype: 'button',
                                text: 'Back'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 0.5,
                        height: 148,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                flex: 1,
                                border: '0 1 0 0',
                                margin: 5,
                                style: 'border-style: solid;',
                                layout: {
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'carousel',
                                        flex: 1,
                                        items: [
                                            {
                                                xtype: 'panel',
                                                layout: {
                                                    type: 'vbox'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Strength'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Dexterity'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Agility'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Fighting'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: ''
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'panel',
                                                layout: {
                                                    type: 'vbox'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Stamina'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Intellect'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Awareness'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Presence'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        flex: 1,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: ''
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                width: '25%'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                margin: 5,
                                layout: {
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'carousel',
                                        flex: 1,
                                        items: [
                                            {
                                                xtype: 'panel',
                                                items: [
                                                    {
                                                        xtype: 'panel',
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Dodge'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Parry'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Toughness'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        height: 20,
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: ''
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Initiative'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'panel',
                                                items: [
                                                    {
                                                        xtype: 'panel',
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Fortitude'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'panel',
                                                        layout: {
                                                            type: 'hbox'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: 'Will'
                                                            },
                                                            {
                                                                xtype: 'panel',
                                                                flex: 1,
                                                                html: '10',
                                                                width: '25%'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 3,
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'carousel',
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'panel',
                                        layout: {
                                            type: 'fit'
                                        },
                                        items: [
                                            {
                                                xtype: 'panel',
                                                border: '1 0 1 0',
                                                cls: [
                                                    'section-header'
                                                ],
                                                docked: 'top',
                                                html: 'Powers',
                                                margin: '',
                                                minHeight: '',
                                                style: 'height:36px; line-height:36px; text-align: center;	font-weight: bold;	border-style: solid; background-color: white;',
                                                ui: 'dark',
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        docked: 'right',
                                                        itemId: 'myimage',
                                                        margin: '3 10 0 0',
                                                        width: 26,
                                                        src: 'resources/images/plus.jpg'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'list',
                                                itemTpl: [
                                                    '<div>',
                                                    '    {power_name} ({rank})',
                                                    '    &nbsp;&nbsp;&nbsp;',
                                                    '    <img src="resources/images/info.jpg" style="vertical-align:bottom" />',
                                                    '</div>'
                                                ],
                                                store: 'CharacterPowerStore',
                                                disableSelection: true,
                                                onItemDisclosure: false
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: {
                                            type: 'fit'
                                        },
                                        items: [
                                            {
                                                xtype: 'panel',
                                                border: '1 0 1 0',
                                                cls: [
                                                    'section-header'
                                                ],
                                                docked: 'top',
                                                html: 'Devices',
                                                style: 'height:36px; line-height:36px; text-align: center;	font-weight: bold;	border-style: solid; background-color: white;',
                                                ui: 'dark',
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        docked: 'right',
                                                        itemId: 'myimage1',
                                                        margin: '3 10 0 0',
                                                        width: 26,
                                                        src: 'resources/images/plus.jpg'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'list',
                                                itemTpl: [
                                                    '<div>List Item {string}</div>'
                                                ],
                                                onItemDisclosure: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: {
                                            type: 'fit'
                                        },
                                        items: [
                                            {
                                                xtype: 'panel',
                                                border: '1 0 1 0',
                                                cls: [
                                                    'section-header'
                                                ],
                                                docked: 'top',
                                                html: 'Skills',
                                                style: 'height:36px; line-height:36px; text-align: center;	font-weight: bold;	border-style: solid; background-color: white;',
                                                ui: 'dark',
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        docked: 'right',
                                                        itemId: 'myimage1',
                                                        margin: '3 10 0 0',
                                                        width: 26,
                                                        src: 'resources/images/plus.jpg'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'list',
                                                itemTpl: [
                                                    '<div>List Item {string}</div>'
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: {
                                            type: 'fit'
                                        },
                                        items: [
                                            {
                                                xtype: 'panel',
                                                border: '1 0 1 0',
                                                cls: [
                                                    'section-header'
                                                ],
                                                docked: 'top',
                                                html: 'Advantages',
                                                style: 'height:36px; line-height:36px; text-align: center;	font-weight: bold;	border-style: solid; background-color: white;',
                                                ui: 'dark',
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        docked: 'right',
                                                        itemId: 'myimage1',
                                                        margin: '3 10 0 0',
                                                        width: 26,
                                                        src: 'resources/images/plus.jpg'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'list',
                                                itemTpl: [
                                                    '<div>List Item {string}</div>'
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: {
                                            type: 'fit'
                                        },
                                        items: [
                                            {
                                                xtype: 'panel',
                                                border: '1 0 1 0',
                                                cls: [
                                                    'section-header'
                                                ],
                                                docked: 'top',
                                                html: 'Complications',
                                                margin: '0 0 0 5',
                                                style: 'height:36px; line-height:36px; text-align: center;	font-weight: bold;	border-style: solid; background-color: white;',
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        docked: 'right',
                                                        itemId: 'myimage3',
                                                        margin: '3 10 0 0',
                                                        width: 26,
                                                        src: 'resources/images/plus.jpg'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'list',
                                                itemTpl: [
                                                    '<div>List Item {string}</div>'
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        title: 'All Powers',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton1',
                                text: 'Cancel'
                            },
                            {
                                xtype: 'button',
                                align: 'right',
                                text: 'Create'
                            }
                        ]
                    },
                    {
                        xtype: 'searchfield',
                        border: '0 0 1 0',
                        itemId: 'power_search',
                        style: 'font-weight: bold;	border-style: solid; background-color: white;',
                        label: 'Name',
                        labelWidth: '20%'
                    },
                    {
                        xtype: 'list',
                        flex: 1,
                        itemId: 'power_list',
                        itemTpl: [
                            '<div>',
                            '    <img src="resources/images/plus.jpg" style="vertical-align:bottom" />',
                            '    &nbsp;&nbsp;&nbsp;',
                            '    {name}',
                            '    &nbsp;&nbsp;&nbsp;',
                            '    <img src="resources/images/info.jpg" style="vertical-align:bottom" />',
                            '</div>'
                        ],
                        store: 'PowerStore',
                        disableSelection: true,
                        grouped: true,
                        onItemDisclosure: false,
                        preventSelectionOnDisclose: false,
                        indexBar: true
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMyimageTap',
                event: 'tap',
                delegate: '#myimage'
            },
            {
                fn: 'onMyimage1Tap',
                event: 'tap',
                delegate: '#myimage1'
            },
            {
                fn: 'onMyimage1Tap2',
                event: 'tap',
                delegate: '#myimage1'
            },
            {
                fn: 'onMyimage1Tap1',
                event: 'tap',
                delegate: '#myimage1'
            },
            {
                fn: 'onMyimage3Tap',
                event: 'tap',
                delegate: '#myimage3'
            },
            {
                fn: 'onMybutton1Tap',
                event: 'tap',
                delegate: '#mybutton1'
            }
        ]
    },

    onMyimageTap: function(img, e, options) {
        var topPanel = img.up('#mainWindow');
        topPanel.setActiveItem(1);
    },

    onMyimage1Tap: function(img, e, options) {
        alert('foo-bar');
    },

    onMyimage1Tap2: function(img, e, options) {
        alert('foo-bar');
    },

    onMyimage1Tap1: function(img, e, options) {
        alert('foo-bar');
    },

    onMyimage3Tap: function(img, e, options) {
        alert('foo-bar');
    },

    onMybutton1Tap: function(button, e, options) {
        var topPanel = button.up('#mainWindow');
        topPanel.getLayout().setAnimation({type: 'slide', direction: 'right'});
        topPanel.setActiveItem(0);
        topPanel.getLayout().setAnimation({type: 'slide', direction: 'left'});
    }

});